version: '3'
services:
  db:
    image: mysql:5.7.32
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Japan
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db:
    driver: local
